version: "3"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Next.js
    restart: on-failure
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
